services:
  hc-blazor:
    image: longnguyen1331/hc-blazor:latest
    container_name: hc-blazor
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/linuxhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - App__SelfUrl=https://dev.benhvien199.vn
      - App__HealthCheckUrl=http://hc-blazor:8080/health-status
      - AuthServer__RequireHttpsMetadata=false      
      - AuthServer__Authority=https://auth-dev.benhvien199.vn/
      - AuthServer__IsOnK8s=true
      - AuthServer__MetaAddress=https://auth-dev.benhvien199.vn
      - RemoteServices__AbpAccountPublic__BaseUrl=https://auth-dev.benhvien199.vn
      - RemoteServices__Default__BaseUrl=https://api-dev.benhvien199.vn
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__Connections__Default__Port=5672
      - RabbitMQ__Connections__Default__UserName=guest
      - RabbitMQ__Connections__Default__Password=guest
    ports:
      - "44302:8081"
      - "8082:8080"
    depends_on:    
      - hc-api
      - rabbitmq
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  hc-api:
    image: longnguyen1331/hc-api:latest
    container_name: hc-api
    hostname: hc-api
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/linuxhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - App__HealthCheckUrl=http://hc-api:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://auth-dev.benhvien199.vn
      - AuthServer__MetaAddress=https://auth-dev.benhvien199.vn
      - App__SelfUrl=https://api-dev.benhvien199.vn
      - ConnectionStrings__Default=User ID=axis;Password=axis;Host=10.65.37.105;Port=5431;Database=postgres;Pooling=false;
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__Connections__Default__Port=5672
      - RabbitMQ__Connections__Default__UserName=guest
      - RabbitMQ__Connections__Default__Password=guest
    ports:
      - "44379:8081"
      - "8083:8080"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  hc-authserver:
    image: longnguyen1331/hc-authserver:latest
    container_name: hc-authserver
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - App__SelfUrl=https://auth-dev.benhvien199.vn
      - App__CorsOrigins=https://dev.benhvien199.vn,https://api-dev.benhvien199.vn,https://auth-dev.benhvien199.vn
      - App__RedirectAllowedUrls=https://dev.benhvien199.vn,https://api-dev.benhvien199.vn,https://auth-dev.benhvien199.vn
      - App__HealthCheckUrl=http://hc-authserver:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://auth-dev.benhvien199.vn
      - Kestrel__Certificates__Default__Path=/app/certs/linuxhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - ConnectionStrings__Default=User ID=axis;Password=axis;Host=10.65.37.105;Port=5431;Database=postgres;Pooling=false;
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__Connections__Default__Port=5672
      - RabbitMQ__Connections__Default__UserName=guest
      - RabbitMQ__Connections__Default__Password=guest
    ports:
      - "44301:8081"
      - "8084:8080"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  db-migrator:
    image: longnguyen1331/hc-db-migrator:latest
    container_name: db-migrator
    environment:
      - OpenIddict__Applications__HC_BlazorServerTiered__RootUrl=https://dev.benhvien199.vn
      - OpenIddict__Applications__HC_Swagger__RootUrl=https://api-dev.benhvien199.vn
      - ConnectionStrings__Default=User ID=axis;Password=axis;Host=10.65.37.105;Port=5431;Database=postgres;Pooling=false;
      - Redis__Configuration=redis
    restart: on-failure
    networks:
      - abp-network
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - abp-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  abp-network:
    name: hc-network
    driver: bridge
