services:
  hc-blazor:
    image: hc-blazor:latest
    container_name: hc-blazor
    build:
      context: ../../
      dockerfile: src/HC.Blazor/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - App__SelfUrl=https://localhost:44302
      - App__HealthCheckUrl=http://hc-blazor:8080/health-status
      - AuthServer__RequireHttpsMetadata=false      
      - AuthServer__Authority=https://localhost:44301/
      - AuthServer__IsOnK8s=true
      - AuthServer__MetaAddress=http://hc-authserver:8080
      - RemoteServices__AbpAccountPublic__BaseUrl=http://hc-authserver:8080 
      - RemoteServices__Default__BaseUrl=http://hc-api:8080
      - Redis__Configuration=redis
    ports:
      - "44302:8081"
    depends_on:    
      - hc-api
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  hc-api:
    image: hc-api:latest
    container_name: hc-api
    hostname: hc-api
    build:
      context: ../../
      dockerfile: src/HC.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - App__HealthCheckUrl=http://hc-api:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://hc-authserver:8080
      - AuthServer__MetaAddress=https://localhost:44301
      - App__SelfUrl=https://localhost:44379
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=HC;Pooling=false;
      - Redis__Configuration=redis
    ports:
      - "44379:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  hc-authserver:
    image: hc-authserver:latest
    container_name: hc-authserver
    build:
      context: ../../
      dockerfile: src/HC.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - App__SelfUrl=https://localhost:44301
      - App__CorsOrigins=https://localhost:44302,https://localhost:44379
      - App__HealthCheckUrl=http://hc-authserver:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44301
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=HC;Pooling=false;
      - Redis__Configuration=redis
    ports:
      - "44301:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  db-migrator:
    image: hc-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/HC.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__HC_BlazorServerTiered__RootUrl=https://localhost:44302
      - OpenIddict__Applications__HC_Swagger__RootUrl=https://localhost:44379
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=HC;Pooling=false;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - abp-network
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      
networks:
  abp-network:
    name: hc-network
    driver: bridge
