services:
  hc-blazor:
    image: longnguyen1331/hc-blazor:latest
    container_name: hc-blazor
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - App__SelfUrl=https://dev.benhvien199.vn
      - App__HealthCheckUrl=http://hc-blazor:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://auth-dev.benhvien199.vn/
      - AuthServer__IsOnK8s=true
      - AuthServer__MetaAddress=http://hc-authserver:8080
      - AuthServer__ClientId=HC_BlazorServer
      - AuthServer__ClientSecret=1q2w3e*
      - RemoteServices__AbpAccountPublic__BaseUrl=http://hc-authserver:8080
      - RemoteServices__Default__BaseUrl=http://hc-api:8080
      - Redis__Configuration=redis
      - App__Cookie__SecurePolicy=Always
      - App__Cookie__SameSite=None
    ports:
      - "44302:8081"
      - "8082:8080"
    depends_on:
      hc-api:
        condition: service_started
      hc-authserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  hc-api:
    image: longnguyen1331/hc-api:latest
    container_name: hc-api
    hostname: hc-api
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - App__SelfUrl=https://api-dev.benhvien199.vn
      - App__HealthCheckUrl=http://hc-api:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://auth-dev.benhvien199.vn/
      - AuthServer__MetaAddress=http://hc-authserver:8080
      - AuthServer__IsOnK8s=true
      - AuthServer__ClientId=HC_Swagger_Prod
      - ConnectionStrings__Default=User ID=postgres;Password=Bv199;Host=113.160.232.208;Port=5400;Database=AxisHCS;Pooling=false;
      - Redis__Configuration=redis
    ports:
      - "44379:8081"
      - "8083:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  hc-authserver:
    image: longnguyen1331/hc-authserver:latest
    container_name: hc-authserver
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - App__SelfUrl=https://auth-dev.benhvien199.vn
      - App__CorsOrigins=https://dev.benhvien199.vn,https://api-dev.benhvien199.vn,https://auth-dev.benhvien199.vn
      - App__RedirectAllowedUrls=https://dev.benhvien199.vn,https://api-dev.benhvien199.vn,https://auth-dev.benhvien199.vn
      - App__HealthCheckUrl=http://hc-authserver:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://auth-dev.benhvien199.vn
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=27a19a3a-9aff-42c5-b8c9-56517f1a626d
      - ConnectionStrings__Default=User ID=postgres;Password=Bv199;Host=113.160.232.208;Port=5400;Database=AxisHCS;Pooling=false;
      - Redis__Configuration=redis
      - App__Cookie__SecurePolicy=Always
      - App__Cookie__SameSite=None
    ports:
      - "44301:8081"
      - "8084:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  # db-migrator:
  #   image: longnguyen1331/hc-db-migrator:latest
  #   container_name: db-migrator
  #   environment:
  #     - OpenIddict__Applications__HC_BlazorServer__ClientId=HC_BlazorServer
  #     - OpenIddict__Applications__HC_BlazorServer__ClientSecret=1q2w3e*
  #     - OpenIddict__Applications__HC_BlazorServer__RootUrl=https://dev.benhvien199.vn
  #     - OpenIddict__Applications__HC_BlazorServer_Prod__ClientId=HC_BlazorServer_Prod
  #     - OpenIddict__Applications__HC_BlazorServer_Prod__ClientSecret=1q2w3e*
  #     - OpenIddict__Applications__HC_BlazorServer_Prod__RootUrl=https://dev.benhvien199.vn
  #     - OpenIddict__Applications__HC_Swagger__RootUrl=https://api-dev.benhvien199.vn
  #     - ConnectionStrings__Default=User ID=postgres;Password=Bv199;Host=113.160.232.208;Port=5400;Database=AxisHCS;Pooling=false;
  #     - Redis__Configuration=redis
  #   restart: on-failure
  #   networks:
  #     - abp-network
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  abp-network:
    name: hc-network
    driver: bridge
